---
title: "Jazz through the years"
author: "Jonas Schoonhoven"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(usethis)
library(spotifyr)
library(compmus)
```

## Column {data-width="500"}

### Made Buble the genre more danceable? 

```{r, results=FALSE}
jazz <- get_playlist_audio_features("", "6W4qNJv2ViwlCElxMIK24H")
MB <- get_playlist_audio_features("", "37i9dQZF1DZ06evO0WqnZe")
FS <- get_playlist_audio_features("", "37i9dQZF1DZ06evO102dNu")
combined <- rbind(MB, FS)
head(combined)

ggplot(combined, aes(x=valence, y=danceability, color=playlist_name)) +
  geom_point(alpha=0.7) +
  expand_limits(x=0, y=0) +
  labs(x="Valence", y="Danceability") +
  theme(legend.position=c(0.8, 0.2))
```

***
Test text

### Same song, different interpretation

```{r}
sinatra <-
  get_tidy_audio_analysis("7FXj7Qg3YorUxdrzvrcY25") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

buble <-
  get_tidy_audio_analysis("7rqSxhVpV4uSKI6WBuToC7") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

compmus_long_distance(
  sinatra |> mutate(pitches = map(pitches, compmus_normalise, "chebyshev")),
  buble |> mutate(pitches = map(pitches, compmus_normalise, "chebyshev")),
  feature = pitches,
  method = "euclidean"
) |>
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = xduration,
      y = ystart + yduration / 2,
      height = yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_equal() +
  labs(x = "Sinatra", y = "Buble") +
  theme_minimal() +
  scale_fill_viridis_c(guide = NULL)
```


### Chart C

```{r}

```
